-- insert to Station

insert into Station (StationID, StationName, StationAddress) values (1, 'Ridgeview', '5968 Chinook Circle');
insert into Station (StationID, StationName, StationAddress) values (2, 'Summerview', '2 Debra Way');
insert into Station (StationID, StationName, StationAddress) values (3, 'Kenwood', '113 Amoth Way');
insert into Station (StationID, StationName, StationAddress) values (4, 'Crownhardt', '7720 Debs Hill');
insert into Station (StationID, StationName, StationAddress) values (5, '6th', '31695 Northland Court');
insert into Station (StationID, StationName, StationAddress) values (6, 'Browning', '32353 Kropf Court');
insert into Station (StationID, StationName, StationAddress) values (7, 'Fairview', '337 Heffernan Plaza');
insert into Station (StationID, StationName, StationAddress) values (8, 'Heffernan', '08 American Hill');
insert into Station (StationID, StationName, StationAddress) values (9, 'John Wall', '61100 Nevada Trail');
insert into Station (StationID, StationName, StationAddress) values (10, 'Di Loreto', '86498 Milwaukee Trail');
insert into Station (StationID, StationName, StationAddress) values (11, 'Northview', '54705 Lillian Lane');
insert into Station (StationID, StationName, StationAddress) values (12, 'Larry', '8 Granby Way');
insert into Station (StationID, StationName, StationAddress) values (13, 'Burrows', '1803 Westport Point');
insert into Station (StationID, StationName, StationAddress) values (14, 'Emmet', '0808 Chive Circle');
insert into Station (StationID, StationName, StationAddress) values (15, 'Mayfield', '308 Lotheville Trail');
insert into Station (StationID, StationName, StationAddress) values (16, '5th', '673 Shoshone Road');
insert into Station (StationID, StationName, StationAddress) values (17, 'Thompson', '77215 Gulseth Pass');
insert into Station (StationID, StationName, StationAddress) values (18, 'Union', '177 Tennyson Way');
insert into Station (StationID, StationName, StationAddress) values (19, 'Debs', '89482 Upham Drive');
insert into Station (StationID, StationName, StationAddress) values (20, 'Center', '12371 Tennessee Hill');
insert into Station (StationID, StationName, StationAddress) values (21, 'Di Loreto', '0661 Thackeray Way');
insert into Station (StationID, StationName, StationAddress) values (22, 'Cody', '29 Toban Trail');
insert into Station (StationID, StationName, StationAddress) values (23, 'Waywood', '1 2nd Center');
insert into Station (StationID, StationName, StationAddress) values (24, 'Longview', '18456 Gerald Hill');
insert into Station (StationID, StationName, StationAddress) values (25, 'Stone Corner', '38419 Logan Plaza');
insert into Station (StationID, StationName, StationAddress) values (26, 'Cambridge', '269 Hoepker Avenue');
insert into Station (StationID, StationName, StationAddress) values (27, 'School', '874 Starling Crossing');
insert into Station (StationID, StationName, StationAddress) values (28, 'Bayside', '893 Crowley Junction');
insert into Station (StationID, StationName, StationAddress) values (29, 'Monument', '96062 Garrison Park');
insert into Station (StationID, StationName, StationAddress) values (30, '1st', '7218 Vernon Circle');
insert into Station (StationID, StationName, StationAddress) values (31, 'Nobel', '2480 Warrior Alley');
insert into Station (StationID, StationName, StationAddress) values (32, 'Fair Oaks', '8 Lawn Drive');
insert into Station (StationID, StationName, StationAddress) values (33, 'Columbus', '66599 Helena Way');
insert into Station (StationID, StationName, StationAddress) values (34, 'Thierer', '0601 Ramsey Lane');
insert into Station (StationID, StationName, StationAddress) values (35, 'Morrow', '901 Morning Park');
insert into Station (StationID, StationName, StationAddress) values (36, 'Dayton', '5 1st Center');
insert into Station (StationID, StationName, StationAddress) values (37, 'Basil', '7216 Claremont Circle');
insert into Station (StationID, StationName, StationAddress) values (38, 'Sage', '1017 Hintze Junction');
insert into Station (StationID, StationName, StationAddress) values (39, 'Westerfield', '69 Buena Vista Avenue');
insert into Station (StationID, StationName, StationAddress) values (40, 'Center', '54 Westerfield Alley');
insert into Station (StationID, StationName, StationAddress) values (41, 'Mallory', '89779 Kenwood Junction');
insert into Station (StationID, StationName, StationAddress) values (42, 'Dawn', '60 Eastlawn Lane');
insert into Station (StationID, StationName, StationAddress) values (43, 'Spohn', '91 Hintze Place');
insert into Station (StationID, StationName, StationAddress) values (44, 'Pawling', '4 Hanson Park');
insert into Station (StationID, StationName, StationAddress) values (45, 'North', '73 Service Pass');
insert into Station (StationID, StationName, StationAddress) values (46, 'Stuart', '279 Sunfield Trail');
insert into Station (StationID, StationName, StationAddress) values (47, 'Pond', '4580 Sloan Park');
insert into Station (StationID, StationName, StationAddress) values (48, 'Melrose', '1 Bluestem Parkway');
insert into Station (StationID, StationName, StationAddress) values (49, 'Tomscot', '508 Boyd Circle');
insert into Station (StationID, StationName, StationAddress) values (50, 'Northridge', '890 Schurz Place');
insert into Station (StationID, StationName, StationAddress) values (51, 'Moulton', '5 Caliangt Way');
insert into Station (StationID, StationName, StationAddress) values (52, 'Di Loreto', '14138 Hudson Trail');
insert into Station (StationID, StationName, StationAddress) values (53, 'Dryden', '9446 Walton Court');
insert into Station (StationID, StationName, StationAddress) values (54, 'Hovde', '0 Bartelt Avenue');
insert into Station (StationID, StationName, StationAddress) values (55, 'Northport', '01900 Mosinee Junction');
insert into Station (StationID, StationName, StationAddress) values (56, 'Elka', '376 Eastwood Crossing');
insert into Station (StationID, StationName, StationAddress) values (57, 'Kropf', '9209 North Center');
insert into Station (StationID, StationName, StationAddress) values (58, 'Dorton', '010 Shopko Crossing');
insert into Station (StationID, StationName, StationAddress) values (59, 'Erie', '414 Comanche Hill');
insert into Station (StationID, StationName, StationAddress) values (60, 'Fremont', '03 Butternut Drive');
insert into Station (StationID, StationName, StationAddress) values (61, 'Calypso', '2 Nevada Parkway');
insert into Station (StationID, StationName, StationAddress) values (62, 'Hoard', '07 Sutherland Terrace');
insert into Station (StationID, StationName, StationAddress) values (63, 'Fordem', '0140 Harper Hill');
insert into Station (StationID, StationName, StationAddress) values (64, 'Kedzie', '88000 Dapin Crossing');
insert into Station (StationID, StationName, StationAddress) values (65, 'Autumn Leaf', '92185 Coolidge Junction');
insert into Station (StationID, StationName, StationAddress) values (66, 'Pond', '9133 Clarendon Crossing');
insert into Station (StationID, StationName, StationAddress) values (67, 'Washington', '21384 Glendale Place');
insert into Station (StationID, StationName, StationAddress) values (68, 'Oxford', '0 Merry Junction');
insert into Station (StationID, StationName, StationAddress) values (69, 'Knutson', '94 Loftsgordon Terrace');
insert into Station (StationID, StationName, StationAddress) values (70, 'Golf Course', '5 Washington Plaza');
insert into Station (StationID, StationName, StationAddress) values (71, 'Riverside', '99399 Lawn Alley');
insert into Station (StationID, StationName, StationAddress) values (72, 'Mosinee', '25545 Debs Place');
insert into Station (StationID, StationName, StationAddress) values (73, 'Coolidge', '0 Roxbury Place');
insert into Station (StationID, StationName, StationAddress) values (74, 'Northwestern', '9563 Cascade Drive');
insert into Station (StationID, StationName, StationAddress) values (75, 'Stoughton', '7434 Dovetail Crossing');
insert into Station (StationID, StationName, StationAddress) values (76, 'Vidon', '33360 Doe Crossing Parkway');
insert into Station (StationID, StationName, StationAddress) values (77, 'Scoville', '45 Loeprich Pass');
insert into Station (StationID, StationName, StationAddress) values (78, 'Montana', '37449 Sage Place');
insert into Station (StationID, StationName, StationAddress) values (79, 'Forest Run', '34 Mcguire Center');
insert into Station (StationID, StationName, StationAddress) values (80, 'Summer Ridge', '43721 Northland Place');
insert into Station (StationID, StationName, StationAddress) values (81, 'Dwight', '482 Express Terrace');
insert into Station (StationID, StationName, StationAddress) values (82, 'Warbler', '83 Westerfield Terrace');
insert into Station (StationID, StationName, StationAddress) values (83, 'Randy', '834 Hanover Street');
insert into Station (StationID, StationName, StationAddress) values (84, 'Sugar', '2 Anniversary Trail');
insert into Station (StationID, StationName, StationAddress) values (85, 'Buena Vista', '4820 Steensland Point');
insert into Station (StationID, StationName, StationAddress) values (86, 'Bartillon', '9793 Warner Circle');
insert into Station (StationID, StationName, StationAddress) values (87, 'Starling', '0 Donald Junction');
insert into Station (StationID, StationName, StationAddress) values (88, 'Corscot', '54155 Mariners Cove Circle');
insert into Station (StationID, StationName, StationAddress) values (89, 'Upham', '382 Barby Avenue');
insert into Station (StationID, StationName, StationAddress) values (90, 'Bonner', '88192 Rigney Place');
insert into Station (StationID, StationName, StationAddress) values (91, 'Orin', '0 Prairie Rose Center');
insert into Station (StationID, StationName, StationAddress) values (92, 'Jenna', '593 Briar Crest Lane');
insert into Station (StationID, StationName, StationAddress) values (93, 'Evergreen', '109 Quincy Center');
insert into Station (StationID, StationName, StationAddress) values (94, 'Anniversary', '75238 Parkside Court');
insert into Station (StationID, StationName, StationAddress) values (95, 'Coleman', '84378 Chive Street');
insert into Station (StationID, StationName, StationAddress) values (96, 'Talmadge', '3632 Barnett Court');
insert into Station (StationID, StationName, StationAddress) values (97, 'Amoth', '04101 Atwood Point');
insert into Station (StationID, StationName, StationAddress) values (98, 'Holmberg', '06826 Commercial Circle');
insert into Station (StationID, StationName, StationAddress) values (99, 'Mosinee', '97408 Sunfield Point');
insert into Station (StationID, StationName, StationAddress) values (100, 'Gina', '329 Kedzie Center');
insert into Station (StationID, StationName, StationAddress) values (101, 'Melby', '64 Walton Hill');
insert into Station (StationID, StationName, StationAddress) values (102, 'Service', '24406 Moose Center');
insert into Station (StationID, StationName, StationAddress) values (103, 'Sachs', '3827 Mesta Plaza');
insert into Station (StationID, StationName, StationAddress) values (104, 'Troy', '97669 Lakewood Gardens Street');
insert into Station (StationID, StationName, StationAddress) values (105, 'Twin Pines', '2 6th Place');
insert into Station (StationID, StationName, StationAddress) values (106, 'Arapahoe', '0 Becker Alley');
insert into Station (StationID, StationName, StationAddress) values (107, 'Parkside', '8280 8th Way');
insert into Station (StationID, StationName, StationAddress) values (108, 'Heath', '0 Armistice Terrace');
insert into Station (StationID, StationName, StationAddress) values (109, 'Waxwing', '5505 Sachs Road');
insert into Station (StationID, StationName, StationAddress) values (110, 'Lakewood', '42597 Village Trail');
insert into Station (StationID, StationName, StationAddress) values (111, 'Atwood', '60158 Forest Dale Park');
insert into Station (StationID, StationName, StationAddress) values (112, 'Clove', '17 Johnson Junction');
insert into Station (StationID, StationName, StationAddress) values (113, 'Heffernan', '0216 Clemons Trail');
insert into Station (StationID, StationName, StationAddress) values (114, 'Tony', '54975 Surrey Plaza');
insert into Station (StationID, StationName, StationAddress) values (115, 'Fair Oaks', '14054 Fuller Drive');
insert into Station (StationID, StationName, StationAddress) values (116, 'Hintze', '56 Elka Terrace');
insert into Station (StationID, StationName, StationAddress) values (117, 'Dottie', '02 Brown Junction');
insert into Station (StationID, StationName, StationAddress) values (118, 'Division', '01874 Bay Way');
insert into Station (StationID, StationName, StationAddress) values (119, 'Quincy', '81931 Jackson Way');
insert into Station (StationID, StationName, StationAddress) values (120, 'Coleman', '20037 Calypso Alley');
insert into Station (StationID, StationName, StationAddress) values (121, 'Judy', '78 Kennedy Point');
insert into Station (StationID, StationName, StationAddress) values (122, 'Evergreen', '846 Kingsford Park');
insert into Station (StationID, StationName, StationAddress) values (123, 'High Crossing', '73645 North Lane');
insert into Station (StationID, StationName, StationAddress) values (124, '6th', '1 Delaware Hill');
insert into Station (StationID, StationName, StationAddress) values (125, 'Meadow Vale', '7 Hooker Circle');
insert into Station (StationID, StationName, StationAddress) values (126, 'Pierstorff', '926 John Wall Junction');
insert into Station (StationID, StationName, StationAddress) values (127, 'Swallow', '5650 Sunbrook Junction');
insert into Station (StationID, StationName, StationAddress) values (128, 'Blue Bill Park', '5764 Maple Way');
insert into Station (StationID, StationName, StationAddress) values (129, 'Paget', '51 Fieldstone Lane');
insert into Station (StationID, StationName, StationAddress) values (130, 'Stuart', '35430 Lotheville Crossing');
insert into Station (StationID, StationName, StationAddress) values (131, 'Bobwhite', '1203 Village Drive');
insert into Station (StationID, StationName, StationAddress) values (132, 'Southridge', '5913 Hudson Crossing');
insert into Station (StationID, StationName, StationAddress) values (133, 'Golf View', '47969 Helena Circle');
insert into Station (StationID, StationName, StationAddress) values (134, 'Kim', '16 Amoth Terrace');
insert into Station (StationID, StationName, StationAddress) values (135, 'Saint Paul', '89 Evergreen Lane');
insert into Station (StationID, StationName, StationAddress) values (136, 'Esch', '47 Corry Plaza');
insert into Station (StationID, StationName, StationAddress) values (137, 'Parkside', '61 Southridge Trail');
insert into Station (StationID, StationName, StationAddress) values (138, 'Colorado', '9 Red Cloud Road');
insert into Station (StationID, StationName, StationAddress) values (139, 'Merry', '967 Pleasure Street');
insert into Station (StationID, StationName, StationAddress) values (140, 'Gulseth', '01033 Spenser Way');
insert into Station (StationID, StationName, StationAddress) values (141, 'Bashford', '48085 Cordelia Point');
insert into Station (StationID, StationName, StationAddress) values (142, 'Vernon', '36 Carioca Alley');
insert into Station (StationID, StationName, StationAddress) values (143, 'Sunnyside', '68 Talmadge Court');
insert into Station (StationID, StationName, StationAddress) values (144, 'Hovde', '3033 Sheridan Plaza');
insert into Station (StationID, StationName, StationAddress) values (145, 'Shelley', '4 Westridge Hill');
insert into Station (StationID, StationName, StationAddress) values (146, 'Randy', '4 Cherokee Court');
insert into Station (StationID, StationName, StationAddress) values (147, 'Kropf', '55985 Browning Court');
insert into Station (StationID, StationName, StationAddress) values (148, 'Crescent Oaks', '1 Walton Lane');
insert into Station (StationID, StationName, StationAddress) values (149, 'Dixon', '00 Dunning Parkway');
insert into Station (StationID, StationName, StationAddress) values (150, 'Fair Oaks', '159 Katie Plaza');
insert into Station (StationID, StationName, StationAddress) values (151, 'Knutson', '4 Old Gate Alley');
insert into Station (StationID, StationName, StationAddress) values (152, 'Crest Line', '0 Eggendart Drive');
insert into Station (StationID, StationName, StationAddress) values (153, 'Moland', '46 Hansons Circle');
insert into Station (StationID, StationName, StationAddress) values (154, 'Westerfield', '172 Hanover Alley');
insert into Station (StationID, StationName, StationAddress) values (155, 'Golf View', '2 Duke Junction');
insert into Station (StationID, StationName, StationAddress) values (156, 'Granby', '96267 Grim Plaza');
insert into Station (StationID, StationName, StationAddress) values (157, 'Atwood', '0 Becker Place');
insert into Station (StationID, StationName, StationAddress) values (158, 'Colorado', '25 Orin Way');
insert into Station (StationID, StationName, StationAddress) values (159, '1st', '77 Hoffman Street');
insert into Station (StationID, StationName, StationAddress) values (160, 'Dorton', '7 Superior Plaza');
insert into Station (StationID, StationName, StationAddress) values (161, 'Spaight', '5700 Roth Crossing');
insert into Station (StationID, StationName, StationAddress) values (162, 'Crowley', '7 Buhler Hill');
insert into Station (StationID, StationName, StationAddress) values (163, 'Express', '793 Crownhardt Way');
insert into Station (StationID, StationName, StationAddress) values (164, 'Longview', '1 Schurz Parkway');
insert into Station (StationID, StationName, StationAddress) values (165, 'Sloan', '5745 Moulton Court');
insert into Station (StationID, StationName, StationAddress) values (166, 'Gerald', '6 Briar Crest Plaza');
insert into Station (StationID, StationName, StationAddress) values (167, 'Forest Dale', '5 Nevada Trail');
insert into Station (StationID, StationName, StationAddress) values (168, 'Westerfield', '5 Warbler Park');
insert into Station (StationID, StationName, StationAddress) values (169, 'Katie', '22 Brickson Park Park');
insert into Station (StationID, StationName, StationAddress) values (170, 'Utah', '61 Calypso Pass');
insert into Station (StationID, StationName, StationAddress) values (171, 'Cardinal', '30 American Ash Pass');
insert into Station (StationID, StationName, StationAddress) values (172, 'Hanover', '123 Grayhawk Place');
insert into Station (StationID, StationName, StationAddress) values (173, 'Troy', '81 Trailsway Plaza');
insert into Station (StationID, StationName, StationAddress) values (174, 'Canary', '462 Mariners Cove Pass');
insert into Station (StationID, StationName, StationAddress) values (175, 'Hudson', '2195 Thierer Point');
insert into Station (StationID, StationName, StationAddress) values (176, 'Aberg', '2 Westend Point');
insert into Station (StationID, StationName, StationAddress) values (177, 'Golf View', '1 Michigan Place');
insert into Station (StationID, StationName, StationAddress) values (178, 'Atwood', '82299 Carberry Point');
insert into Station (StationID, StationName, StationAddress) values (179, 'Morning', '10 Dapin Road');
insert into Station (StationID, StationName, StationAddress) values (180, 'Meadow Ridge', '392 North Way');
insert into Station (StationID, StationName, StationAddress) values (181, 'Holy Cross', '2 7th Road');
insert into Station (StationID, StationName, StationAddress) values (182, 'Rockefeller', '5 Michigan Center');
insert into Station (StationID, StationName, StationAddress) values (183, 'Pawling', '1678 Buena Vista Crossing');
insert into Station (StationID, StationName, StationAddress) values (184, 'Nevada', '3 Charing Cross Way');
insert into Station (StationID, StationName, StationAddress) values (185, 'Old Shore', '479 Little Fleur Plaza');
insert into Station (StationID, StationName, StationAddress) values (186, 'Clemons', '5072 Jay Center');
insert into Station (StationID, StationName, StationAddress) values (187, 'Moose', '390 Derek Parkway');
insert into Station (StationID, StationName, StationAddress) values (188, 'Sutherland', '3549 Dakota Drive');
insert into Station (StationID, StationName, StationAddress) values (189, 'Arizona', '2099 Carpenter Avenue');
insert into Station (StationID, StationName, StationAddress) values (190, 'Kensington', '54910 Ilene Lane');
insert into Station (StationID, StationName, StationAddress) values (191, 'Starling', '9 Eastlawn Center');
insert into Station (StationID, StationName, StationAddress) values (192, 'Fallview', '1272 Kinsman Junction');
insert into Station (StationID, StationName, StationAddress) values (193, 'Debra', '2 Thompson Lane');
insert into Station (StationID, StationName, StationAddress) values (194, 'Badeau', '0 Forest Alley');
insert into Station (StationID, StationName, StationAddress) values (195, 'Shoshone', '8 Prairieview Parkway');
insert into Station (StationID, StationName, StationAddress) values (196, 'Sage', '3 Lakewood Pass');
insert into Station (StationID, StationName, StationAddress) values (197, 'Dixon', '211 Burrows Road');
insert into Station (StationID, StationName, StationAddress) values (198, 'Elka', '90 Hooker Plaza');
insert into Station (StationID, StationName, StationAddress) values (199, 'Harbort', '771 Packers Crossing');
insert into Station (StationID, StationName, StationAddress) values (200, 'Schlimgen', '1 Waxwing Street');
insert into Station (StationID, StationName, StationAddress) values (201, 'Harper', '982 Meadow Ridge Circle');
insert into Station (StationID, StationName, StationAddress) values (202, 'New Castle', '98522 Everett Road');
insert into Station (StationID, StationName, StationAddress) values (203, 'Main', '5037 Mosinee Alley');
insert into Station (StationID, StationName, StationAddress) values (204, 'Comanche', '48334 Welch Road');
insert into Station (StationID, StationName, StationAddress) values (205, 'Green Ridge', '4218 Marcy Lane');
insert into Station (StationID, StationName, StationAddress) values (206, 'Mariners Cove', '6359 Porter Place');
insert into Station (StationID, StationName, StationAddress) values (207, 'Hoard', '8528 Spohn Avenue');
insert into Station (StationID, StationName, StationAddress) values (208, 'Dwight', '8 Forest Run Crossing');
insert into Station (StationID, StationName, StationAddress) values (209, 'Park Meadow', '7262 Gulseth Point');
insert into Station (StationID, StationName, StationAddress) values (210, 'Bartelt', '224 Hudson Avenue');
insert into Station (StationID, StationName, StationAddress) values (211, 'Magdeline', '6 Harbort Park');
insert into Station (StationID, StationName, StationAddress) values (212, 'Service', '9 Del Sol Point');
insert into Station (StationID, StationName, StationAddress) values (213, 'Hoepker', '9459 Lillian Center');
insert into Station (StationID, StationName, StationAddress) values (214, 'Tony', '23 Westerfield Parkway');
insert into Station (StationID, StationName, StationAddress) values (215, 'Nancy', '87 Butternut Street');
insert into Station (StationID, StationName, StationAddress) values (216, 'Macpherson', '56947 Colorado Plaza');
insert into Station (StationID, StationName, StationAddress) values (217, 'Redwing', '60 Upham Hill');
insert into Station (StationID, StationName, StationAddress) values (218, 'Harbort', '85265 Tony Road');
insert into Station (StationID, StationName, StationAddress) values (219, 'Comanche', '26294 Nancy Avenue');
insert into Station (StationID, StationName, StationAddress) values (220, 'Forest Dale', '33601 Killdeer Trail');
insert into Station (StationID, StationName, StationAddress) values (221, '2nd', '51 Becker Way');
insert into Station (StationID, StationName, StationAddress) values (222, 'Summer Ridge', '9 Crownhardt Park');
insert into Station (StationID, StationName, StationAddress) values (223, 'Tony', '5834 Southridge Court');
insert into Station (StationID, StationName, StationAddress) values (224, 'Dexter', '1515 Monica Street');
insert into Station (StationID, StationName, StationAddress) values (225, 'Rieder', '3 Westerfield Plaza');
insert into Station (StationID, StationName, StationAddress) values (226, 'Elmside', '5094 Fairfield Place');
insert into Station (StationID, StationName, StationAddress) values (227, 'Northwestern', '53163 Summer Ridge Crossing');
insert into Station (StationID, StationName, StationAddress) values (228, 'Main', '0317 Continental Drive');
insert into Station (StationID, StationName, StationAddress) values (229, 'Straubel', '290 Nelson Terrace');
insert into Station (StationID, StationName, StationAddress) values (230, 'Ridgeway', '02 Corscot Court');
insert into Station (StationID, StationName, StationAddress) values (231, 'Sheridan', '1418 Rockefeller Hill');
insert into Station (StationID, StationName, StationAddress) values (232, 'Bunting', '99 Florence Pass');
insert into Station (StationID, StationName, StationAddress) values (233, 'Thierer', '8276 Glacier Hill Court');
insert into Station (StationID, StationName, StationAddress) values (234, 'Comanche', '06 Hollow Ridge Pass');
insert into Station (StationID, StationName, StationAddress) values (235, 'Fordem', '0 Mcbride Junction');
insert into Station (StationID, StationName, StationAddress) values (236, 'Glendale', '7418 Menomonie Parkway');
insert into Station (StationID, StationName, StationAddress) values (237, 'Nova', '8 Acker Crossing');
insert into Station (StationID, StationName, StationAddress) values (238, 'Oak Valley', '0616 Mcbride Drive');
insert into Station (StationID, StationName, StationAddress) values (239, 'Comanche', '2 Northfield Avenue');
insert into Station (StationID, StationName, StationAddress) values (240, 'Pine View', '26348 Summit Way');
insert into Station (StationID, StationName, StationAddress) values (241, 'Hermina', '7271 Derek Court');
insert into Station (StationID, StationName, StationAddress) values (242, 'Springview', '6 Loomis Street');
insert into Station (StationID, StationName, StationAddress) values (243, 'Westport', '5 Esker Way');
insert into Station (StationID, StationName, StationAddress) values (244, 'Pine View', '19 Clove Place');
insert into Station (StationID, StationName, StationAddress) values (245, 'Eastlawn', '81 Maywood Drive');
insert into Station (StationID, StationName, StationAddress) values (246, 'Briar Crest', '83313 Helena Drive');
insert into Station (StationID, StationName, StationAddress) values (247, 'Dryden', '30 Banding Center');
insert into Station (StationID, StationName, StationAddress) values (248, 'Grayhawk', '50858 Victoria Terrace');
insert into Station (StationID, StationName, StationAddress) values (249, 'Grover', '021 Riverside Road');
insert into Station (StationID, StationName, StationAddress) values (250, 'Gerald', '2 Westport Circle');
insert into Station (StationID, StationName, StationAddress) values (251, 'Maple Wood', '390 Morning Lane');
insert into Station (StationID, StationName, StationAddress) values (252, 'New Castle', '4 Eggendart Lane');
insert into Station (StationID, StationName, StationAddress) values (253, 'Truax', '1764 Prentice Parkway');
insert into Station (StationID, StationName, StationAddress) values (254, 'Tennessee', '5686 Haas Park');
insert into Station (StationID, StationName, StationAddress) values (255, 'Kenwood', '8345 Northland Circle');
insert into Station (StationID, StationName, StationAddress) values (256, 'Ridge Oak', '09051 American Ash Park');
insert into Station (StationID, StationName, StationAddress) values (257, 'Sherman', '948 Melrose Center');
insert into Station (StationID, StationName, StationAddress) values (258, 'Cascade', '284 Park Meadow Plaza');
insert into Station (StationID, StationName, StationAddress) values (259, 'Bay', '45 Ilene Place');
insert into Station (StationID, StationName, StationAddress) values (260, 'Bartillon', '42 Little Fleur Parkway');
insert into Station (StationID, StationName, StationAddress) values (261, 'Ryan', '4 Raven Street');
insert into Station (StationID, StationName, StationAddress) values (262, 'Artisan', '88 Huxley Parkway');
insert into Station (StationID, StationName, StationAddress) values (263, 'Longview', '65238 Bowman Pass');
insert into Station (StationID, StationName, StationAddress) values (264, 'Main', '780 American Ash Place');
insert into Station (StationID, StationName, StationAddress) values (265, 'Badeau', '28653 Longview Park');
insert into Station (StationID, StationName, StationAddress) values (266, 'Valley Edge', '490 Kinsman Street');
insert into Station (StationID, StationName, StationAddress) values (267, 'Cardinal', '9 Gateway Plaza');
insert into Station (StationID, StationName, StationAddress) values (268, 'Pennsylvania', '2218 Del Mar Lane');
insert into Station (StationID, StationName, StationAddress) values (269, 'Bay', '25 Dapin Center');
insert into Station (StationID, StationName, StationAddress) values (270, 'Canary', '7 Kensington Hill');
insert into Station (StationID, StationName, StationAddress) values (271, 'Moulton', '264 Northland Alley');
insert into Station (StationID, StationName, StationAddress) values (272, 'Melby', '5 Magdeline Center');
insert into Station (StationID, StationName, StationAddress) values (273, 'Montana', '071 Annamark Road');
insert into Station (StationID, StationName, StationAddress) values (274, 'Trailsway', '24446 Maple Trail');
insert into Station (StationID, StationName, StationAddress) values (275, 'Mendota', '51550 Vera Hill');
insert into Station (StationID, StationName, StationAddress) values (276, 'Riverside', '91 Petterle Avenue');
insert into Station (StationID, StationName, StationAddress) values (277, 'Merchant', '512 Iowa Plaza');
insert into Station (StationID, StationName, StationAddress) values (278, 'Doe Crossing', '7619 Marcy Crossing');
insert into Station (StationID, StationName, StationAddress) values (279, 'Almo', '9 Graedel Pass');
insert into Station (StationID, StationName, StationAddress) values (280, 'Crescent Oaks', '49633 Mallard Lane');
insert into Station (StationID, StationName, StationAddress) values (281, 'Sauthoff', '260 Sage Street');
insert into Station (StationID, StationName, StationAddress) values (282, 'Loftsgordon', '280 Scott Way');
insert into Station (StationID, StationName, StationAddress) values (283, 'Del Sol', '0758 Harbort Terrace');
insert into Station (StationID, StationName, StationAddress) values (284, 'Fuller', '76619 Longview Road');
insert into Station (StationID, StationName, StationAddress) values (285, 'Mosinee', '11 Johnson Road');
insert into Station (StationID, StationName, StationAddress) values (286, 'Nevada', '70 Mcbride Avenue');
insert into Station (StationID, StationName, StationAddress) values (287, 'John Wall', '4 Hoepker Parkway');
insert into Station (StationID, StationName, StationAddress) values (288, 'Springs', '3 Butternut Lane');
insert into Station (StationID, StationName, StationAddress) values (289, 'Anniversary', '641 Buell Lane');
insert into Station (StationID, StationName, StationAddress) values (290, 'Nelson', '74 Trailsway Road');
insert into Station (StationID, StationName, StationAddress) values (291, 'Continental', '404 Manley Park');
insert into Station (StationID, StationName, StationAddress) values (292, 'Heffernan', '0084 Cottonwood Pass');
insert into Station (StationID, StationName, StationAddress) values (293, 'Carberry', '84189 8th Avenue');
insert into Station (StationID, StationName, StationAddress) values (294, 'Graceland', '07641 Hoffman Center');
insert into Station (StationID, StationName, StationAddress) values (295, 'Huxley', '40 Spenser Circle');
insert into Station (StationID, StationName, StationAddress) values (296, 'Goodland', '9 Truax Way');
insert into Station (StationID, StationName, StationAddress) values (297, 'Forest', '10869 Roth Street');
insert into Station (StationID, StationName, StationAddress) values (298, 'Truax', '0 Spaight Point');
insert into Station (StationID, StationName, StationAddress) values (299, 'South', '1 Union Court');
insert into Station (StationID, StationName, StationAddress) values (300, 'Mallory', '31536 Barby Lane');
insert into Station (StationID, StationName, StationAddress) values (301, 'Commercial', '72 Veith Junction');
insert into Station (StationID, StationName, StationAddress) values (302, 'Kensington', '234 Hollow Ridge Street');
insert into Station (StationID, StationName, StationAddress) values (303, 'Northfield', '0458 Erie Parkway');
insert into Station (StationID, StationName, StationAddress) values (304, 'Burrows', '761 Dennis Road');
insert into Station (StationID, StationName, StationAddress) values (305, 'Longview', '68 Eggendart Junction');
insert into Station (StationID, StationName, StationAddress) values (306, 'Jenna', '3 Crownhardt Pass');
insert into Station (StationID, StationName, StationAddress) values (307, 'Fairview', '63911 Florence Street');
insert into Station (StationID, StationName, StationAddress) values (308, 'Stuart', '5 Pierstorff Drive');
insert into Station (StationID, StationName, StationAddress) values (309, '2nd', '23819 Pankratz Plaza');
insert into Station (StationID, StationName, StationAddress) values (310, 'Petterle', '22661 Becker Avenue');
insert into Station (StationID, StationName, StationAddress) values (311, 'Truax', '9196 Bashford Circle');
insert into Station (StationID, StationName, StationAddress) values (312, 'Mendota', '641 Grayhawk Lane');
insert into Station (StationID, StationName, StationAddress) values (313, 'Hanson', '3098 Gateway Circle');
insert into Station (StationID, StationName, StationAddress) values (314, 'Moulton', '5 Mifflin Plaza');
insert into Station (StationID, StationName, StationAddress) values (315, 'Forest', '8 Rigney Pass');
insert into Station (StationID, StationName, StationAddress) values (316, 'Colorado', '27 Prairie Rose Trail');
insert into Station (StationID, StationName, StationAddress) values (317, 'Saint Paul', '17 Heath Hill');
insert into Station (StationID, StationName, StationAddress) values (318, 'Evergreen', '0 Westend Junction');
insert into Station (StationID, StationName, StationAddress) values (319, 'Nevada', '262 Sachs Pass');
insert into Station (StationID, StationName, StationAddress) values (320, 'Myrtle', '4456 Gulseth Terrace');
insert into Station (StationID, StationName, StationAddress) values (321, 'Calypso', '885 Judy Street');
insert into Station (StationID, StationName, StationAddress) values (322, 'Emmet', '8 Pepper Wood Trail');
insert into Station (StationID, StationName, StationAddress) values (323, 'Pankratz', '503 Luster Terrace');
insert into Station (StationID, StationName, StationAddress) values (324, 'Springview', '5685 Ramsey Plaza');
insert into Station (StationID, StationName, StationAddress) values (325, 'Haas', '80728 Hanover Circle');
insert into Station (StationID, StationName, StationAddress) values (326, 'Maple', '1071 Hayes Park');
insert into Station (StationID, StationName, StationAddress) values (327, 'Trailsway', '259 Lakeland Junction');
insert into Station (StationID, StationName, StationAddress) values (328, 'Manley', '1497 Bobwhite Avenue');
insert into Station (StationID, StationName, StationAddress) values (329, 'Nova', '9921 Walton Alley');
insert into Station (StationID, StationName, StationAddress) values (330, 'Mesta', '183 Bowman Junction');
insert into Station (StationID, StationName, StationAddress) values (331, 'Vera', '9 Debra Center');
insert into Station (StationID, StationName, StationAddress) values (332, 'Mallory', '34040 Oak Valley Parkway');
insert into Station (StationID, StationName, StationAddress) values (333, 'Mockingbird', '18576 Lunder Parkway');
insert into Station (StationID, StationName, StationAddress) values (334, 'Graceland', '1033 Ilene Street');
insert into Station (StationID, StationName, StationAddress) values (335, 'Carpenter', '25 Daystar Lane');
insert into Station (StationID, StationName, StationAddress) values (336, 'Prentice', '231 Colorado Avenue');
insert into Station (StationID, StationName, StationAddress) values (337, 'Hoepker', '41 Green Ridge Crossing');
insert into Station (StationID, StationName, StationAddress) values (338, 'Mcguire', '4708 Packers Court');
insert into Station (StationID, StationName, StationAddress) values (339, '4th', '47 Farmco Way');
insert into Station (StationID, StationName, StationAddress) values (340, 'Shopko', '59 Lawn Park');
insert into Station (StationID, StationName, StationAddress) values (341, 'Derek', '098 Boyd Terrace');
insert into Station (StationID, StationName, StationAddress) values (342, 'Welch', '0 Lakewood Terrace');
insert into Station (StationID, StationName, StationAddress) values (343, 'Moulton', '220 Golf Course Park');
insert into Station (StationID, StationName, StationAddress) values (344, 'Toban', '44855 Brickson Park Pass');
insert into Station (StationID, StationName, StationAddress) values (345, 'Iowa', '69348 Donald Pass');
insert into Station (StationID, StationName, StationAddress) values (346, 'Claremont', '06 Meadow Ridge Hill');
insert into Station (StationID, StationName, StationAddress) values (347, 'Village Green', '782 Nobel Junction');
insert into Station (StationID, StationName, StationAddress) values (348, 'Farmco', '09 Longview Alley');
insert into Station (StationID, StationName, StationAddress) values (349, 'Nova', '629 Garrison Hill');
insert into Station (StationID, StationName, StationAddress) values (350, 'John Wall', '219 Lerdahl Place');
insert into Station (StationID, StationName, StationAddress) values (351, '2nd', '765 Iowa Circle');
insert into Station (StationID, StationName, StationAddress) values (352, 'Lake View', '1 Butternut Point');
insert into Station (StationID, StationName, StationAddress) values (353, 'Truax', '8 Bunker Hill Trail');
insert into Station (StationID, StationName, StationAddress) values (354, 'Carey', '68597 Truax Parkway');
insert into Station (StationID, StationName, StationAddress) values (355, 'Commercial', '5 Fisk Road');
insert into Station (StationID, StationName, StationAddress) values (356, 'Vidon', '6 Paget Point');
insert into Station (StationID, StationName, StationAddress) values (357, 'Alpine', '94 Talmadge Crossing');
insert into Station (StationID, StationName, StationAddress) values (358, 'Vidon', '01 Maple Wood Pass');
insert into Station (StationID, StationName, StationAddress) values (359, 'Oxford', '20675 Crescent Oaks Point');
insert into Station (StationID, StationName, StationAddress) values (360, 'Mayfield', '98680 Stephen Center');
insert into Station (StationID, StationName, StationAddress) values (361, 'Oak Valley', '098 Fremont Center');
insert into Station (StationID, StationName, StationAddress) values (362, 'Everett', '32 Troy Terrace');
insert into Station (StationID, StationName, StationAddress) values (363, 'Debra', '23 3rd Avenue');
insert into Station (StationID, StationName, StationAddress) values (364, 'Loomis', '0 Birchwood Pass');
insert into Station (StationID, StationName, StationAddress) values (365, 'Cambridge', '4 Swallow Street');
insert into Station (StationID, StationName, StationAddress) values (366, 'Thierer', '84809 Mccormick Hill');
insert into Station (StationID, StationName, StationAddress) values (367, 'Dunning', '6434 Northland Center');
insert into Station (StationID, StationName, StationAddress) values (368, 'Golden Leaf', '012 Stephen Park');
insert into Station (StationID, StationName, StationAddress) values (369, 'Debs', '70628 Oxford Point');
insert into Station (StationID, StationName, StationAddress) values (370, 'Portage', '17 Waubesa Parkway');
insert into Station (StationID, StationName, StationAddress) values (371, 'Nobel', '1096 Lighthouse Bay Crossing');
insert into Station (StationID, StationName, StationAddress) values (372, 'Golden Leaf', '65 Westridge Alley');
insert into Station (StationID, StationName, StationAddress) values (373, 'Sauthoff', '3 Homewood Center');
insert into Station (StationID, StationName, StationAddress) values (374, 'Hallows', '4730 Barnett Center');
insert into Station (StationID, StationName, StationAddress) values (375, 'Mockingbird', '66 Hintze Hill');
insert into Station (StationID, StationName, StationAddress) values (376, 'Little Fleur', '09 Raven Trail');
insert into Station (StationID, StationName, StationAddress) values (377, 'Stuart', '21219 Delladonna Court');
insert into Station (StationID, StationName, StationAddress) values (378, 'Packers', '5 Longview Drive');
insert into Station (StationID, StationName, StationAddress) values (379, 'Morrow', '68722 Ohio Circle');
insert into Station (StationID, StationName, StationAddress) values (380, 'Fisk', '356 Scoville Crossing');
insert into Station (StationID, StationName, StationAddress) values (381, 'West', '599 Nova Park');
insert into Station (StationID, StationName, StationAddress) values (382, 'Springview', '2297 Fieldstone Road');
insert into Station (StationID, StationName, StationAddress) values (383, 'Gulseth', '5 Macpherson Junction');
insert into Station (StationID, StationName, StationAddress) values (384, 'Division', '008 Ridgeview Hill');
insert into Station (StationID, StationName, StationAddress) values (385, 'Center', '105 Messerschmidt Place');
insert into Station (StationID, StationName, StationAddress) values (386, 'Merry', '4 Beilfuss Road');
insert into Station (StationID, StationName, StationAddress) values (387, 'Alpine', '80304 Sauthoff Alley');
insert into Station (StationID, StationName, StationAddress) values (388, 'Meadow Ridge', '399 Canary Trail');
insert into Station (StationID, StationName, StationAddress) values (389, 'Declaration', '69 Ilene Place');
insert into Station (StationID, StationName, StationAddress) values (390, 'Transport', '50648 Michigan Lane');
insert into Station (StationID, StationName, StationAddress) values (391, 'Farmco', '6 Hoffman Parkway');
insert into Station (StationID, StationName, StationAddress) values (392, 'Banding', '4 Towne Trail');
insert into Station (StationID, StationName, StationAddress) values (393, 'Briar Crest', '175 Carey Parkway');
insert into Station (StationID, StationName, StationAddress) values (394, 'Old Gate', '81644 Mcbride Circle');
insert into Station (StationID, StationName, StationAddress) values (395, 'Upham', '41166 Atwood Point');
insert into Station (StationID, StationName, StationAddress) values (396, 'Sundown', '56 Holy Cross Trail');
insert into Station (StationID, StationName, StationAddress) values (397, 'Ronald Regan', '53701 Blackbird Road');
insert into Station (StationID, StationName, StationAddress) values (398, 'Melby', '876 Maple Wood Place');
insert into Station (StationID, StationName, StationAddress) values (399, 'Schlimgen', '17006 Spenser Point');
insert into Station (StationID, StationName, StationAddress) values (400, 'Westerfield', '1 Atwood Road');
