--
-- Target: Oracle 
-- Syntax: sqlplus user@tnsnames_entry/password @filename.sql
-- 
-- Date  : May 21 2024 20:26
-- Script Generated by Database Design Studio 2.21.3 
--


--
-- Create Table    : 'Bus'   
-- BusID           :  
-- Model           :  
-- Capacity       :  
-- PurchaseDate    :  
-- 

CREATE TABLE Bus (
    BusID          NUMBER(38) NOT NULL,
    Model          VARCHAR2(100) NOT NULL,
    Capacity       NUMBER(38) NOT NULL,
    PurchaseDate   DATE NOT NULL,
CONSTRAINT pk_Bus PRIMARY KEY (BusID))
/
--
-- Create Table    : 'Driver'   
-- DriverID        :  
-- FullName        :  
-- LicenseNumber   :  
-- HireDate        :  
--

  CREATE TABLE Driver (
      DriverID       NUMBER(38) NOT NULL,
      FullName       VARCHAR2(100) NOT NULL,
      LicenseNumber  VARCHAR2(50) NOT NULL UNIQUE,
      HireDate       DATE NOT NULL,
  CONSTRAINT pk_Driver PRIMARY KEY (DriverID))
/
--
-- Create Table    : 'Station'   
-- StationID       :  
-- StationName     :  
-- StationAddress  :  
--
CREATE TABLE Station (
    StationID      NUMBER(38),
    StationName    VARCHAR2(100) NOT NULL,
    StationAddress VARCHAR2(255) NOT NULL,
CONSTRAINT pk_Station PRIMARY KEY (StationID))
/
--
-- Create Table    : 'Route'   
-- RouteID         :  
-- RouteName       :  
-- StartStationID  :  
-- EndStationID    :  
-- StationID       :  (references Station.StationID)
-- StationID1      :  (references Station.StationID)
--
CREATE TABLE Route (
    RouteID        NUMBER(38) NOT NULL,
    RouteName      VARCHAR2(100) NOT NULL,
    StartStationID NUMBER(38) NOT NULL,
    EndStationID   NUMBER(38) NOT NULL,
CONSTRAINT pk_Route PRIMARY KEY (RouteID),
CONSTRAINT fk_Route FOREIGN KEY (StartStationID)
    REFERENCES Station (StationID),
CONSTRAINT fk_Route2 FOREIGN KEY (EndStationID)
    REFERENCES Station (StationID))
/
--
-- Create Table    : 'Schedule'   
-- ScheduleID      :  
-- RouteID         :  
-- DepartureTime   :  
-- RouteID1        :  (references Route.RouteID)
--
CREATE TABLE Schedule (
    ScheduleID     NUMBER(38) NOT NULL,
    RouteID        NUMBER(38) NOT NULL,
    DepartureTime  TIMESTAMP NOT NULL,
  ArrivalTime  TIMESTAMP NOT NULL,
CONSTRAINT pk_Schedule PRIMARY KEY (ScheduleID),
CONSTRAINT fk_Schedule FOREIGN KEY (RouteID)
    REFERENCES Route (RouteID)
    ON DELETE CASCADE)
/
--
-- Create Table    : 'Trip'   
-- TripID          :  
-- BusID           :  
-- DriverID        :  
-- TripDate        : 
-- RouteID 
-- BusID          :  (references Bus.BusID)
-- DriverID       :  (references Driver.DriverID)
-- RouteID         :  (references Route.RouteID)
--
CREATE TABLE Trip (
    TripID         NUMBER(38) NOT NULL,
    BusID          NUMBER(38) NOT NULL,
    DriverID       NUMBER(38) NOT NULL,
    TripDate       DATE NOT NULL,
    RouteID        NUMBER(38) NOT NULL,
CONSTRAINT pk_Trip PRIMARY KEY (TripID),
CONSTRAINT fk_Trip FOREIGN KEY (BusID)
    REFERENCES Bus (BusID),
CONSTRAINT fk_Trip2 FOREIGN KEY (DriverID)
    REFERENCES Driver (DriverID),
CONSTRAINT fk_Trip3 FOREIGN KEY (RouteID)
    REFERENCES Route (RouteID))
